# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eca54680a186f98b062d4848a83a7c7ce03321dbb10aa81c9b229071767d2285f4929adcf2ffb5b1d9d0da54a79e7d75ea87daf95dc71fa05d0e56f2854910c

test:
  secret_key_base: 769e3a29780c72ee518a5cfb8a2548271e860c4f6ca54fe7fd8ab5018fff9881cbd9ca32e3d023abc94dcc3125a0b6276970bbbc1688f77ac4c251af7bbb4713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
